=== shree-29/Net-centric/q3.dtd
<!ELEMENT application (applicant+)>
<!ELEMENT applicant (applicant_name,prefix,first_name,last_name,organization,title,telephone,
academic_perf,intellectual_ability,ability_to_express,motivation_for_proposed_field,admit,full_legal_name)>

<!ELEMENT applicant_name (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT organization (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT academic_perf (#PCDATA)>
<!ELEMENT intellectual_ability (#PCDATA)>
<!ELEMENT ability_to_express (#PCDATA)>
<!ELEMENT motivation_for_proposed_field (#PCDATA)>
<!ELEMENT admit (#PCDATA)>
<!ELEMENT full_legal_name (#PCDATA)>


<!ATTLIST applicant id CDATA #REQUIRED>
<!ATTLIST prefix p (Mr.|Mrs.|Dr.) "Dr.">
<!ATTLIST admit option (Assuredly|Probably| Possibly| No) "Assuredly">

=== shree-29/Net-centric/q3.xml
<?xml version="1.0"?>
<!DOCTYPE application SYSTEM "q3.dtd">

<application>
    <applicant id="1">
        <applicant_name>shree</applicant_name>
        <prefix p="Mr."></prefix>
        <first_name>Thangavelu</first_name>
        <last_name>T</last_name>
        <organization>amrita</organization>
        <title>associate professor</title>
        <telephone>6380076653</telephone>
        <academic_perf ></academic_perf>
        <intellectual_ability ></intellectual_ability>
        <ability_to_express ></ability_to_express>
        <motivation_for_proposed_field ></motivation_for_proposed_field>
        <admit option="Assuredly"></admit>
        <full_legal_name>shree k k</full_legal_name>
    </applicant>
</application>
